module.exports = {
  ROLES: {
    PATIENT: "patient",
    DOCTOR: "doctor",
    ADMIN: "admin",
    OPERATOR: "operator",
  },
  REG_STATUS: {
    NONE: 0,
    PENDING: 1,
    APPROVED: 2,
    REJECTED: 3,
    ACTIVE: 4,
    DEACTIVATED: 5,
  },
  DOC_STATUS: {
    NONE: 0,
    PENDING: 1,
    VERIFIED: 2,
    REJECTED: 3,
    SUSPENDED: 4,
  },
  RECORD_TYPES: {
    LAB_REPORT: 0,
    PRESCRIPTION: 1,
    IMAGING: 2,
    DIAGNOSIS: 3,
    VACCINATION: 4,
    SURGERY: 5,
    DISCHARGE: 6,
    OTHER: 7,
  },
  ACCESS_LEVELS: {
    NONE: 0,
    READ_ONLY: 1,
    READ_WRITE: 2,
    EMERGENCY: 3,
  },
  CONSENT_ACTIONS: {
    GRANTED: 0,
    REVOKED: 1,
    EXPIRED: 2,
    EMERGENCY: 3,
    REQUESTED: 4,
    APPROVED: 5,
    REJECTED: 6,
  },
  VALID_BLOOD_TYPES: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", ""],
  VALID_SPECIALIZATIONS: [
    "Cardiology", "Neurology", "Orthopedics", "Pediatrics",
    "Dermatology", "Oncology", "Psychiatry", "Surgery",
    "Radiology", "Gynecology", "Urology", "ENT",
    "Ophthalmology", "GeneralMedicine", "Dentistry", "Physiotherapy", "Other",
  ],
};
